#ifndef _SYNTH_HEADER

#define _SYNTH_HEADER

#define SYNTH_NOT_FOUND	-1
#define SYNTH_FOREIGNKEY_FOREIGNKEY	  0
#define SYNTH_TABLE_AVGROWLENGTH	  1
#define SYNTH_TABLE_CHECKSUM	  2
#define SYNTH_TABLE_COLUMNS	  3
#define SYNTH_TABLE_COLUMN_AUTOINCREMENT	  4
#define SYNTH_TABLE_COLUMN_CHARACTERSETNAME	  5
#define SYNTH_TABLE_COLUMN_COLLATIONNAME	  6
#define SYNTH_TABLE_COLUMN_COMMENT	  7
#define SYNTH_TABLE_COLUMN_DATATYPEEXPLICITPARAMS	  8
#define SYNTH_TABLE_COLUMN_DEFAULTVALUE	  9
#define SYNTH_TABLE_COLUMN_DEFAULTVALUEISNULL	 10
#define SYNTH_TABLE_COLUMN_ISNOTNULL	 11
#define SYNTH_TABLE_COLUMN_LENGTH	 12
#define SYNTH_TABLE_COLUMN_NAME	 13
#define SYNTH_TABLE_COLUMN_OLDNAME	 14
#define SYNTH_TABLE_COLUMN_OWNER	 15
#define SYNTH_TABLE_COLUMN_PRECISION	 16
#define SYNTH_TABLE_COLUMN_SCALE	 17
#define SYNTH_TABLE_COLUMN_SIMPLETYPE	 18
#define SYNTH_TABLE_COMMENT	 19
#define SYNTH_TABLE_COMMENTEDOUT	 20
#define SYNTH_TABLE_CONNECTIONSTRING	 21
#define SYNTH_TABLE_CREATEDATE	 22
#define SYNTH_TABLE_DEFAULTCHARACTERSETNAME	 23
#define SYNTH_TABLE_DEFAULTCOLLATIONNAME	 24
#define SYNTH_TABLE_DELAYKEYWRITE	 25
#define SYNTH_TABLE_FOREIGNKEYS	 26
#define SYNTH_TABLE_FOREIGNKEY_COLUMNS	 27
#define SYNTH_TABLE_FOREIGNKEY_COMMENT	 28
#define SYNTH_TABLE_FOREIGNKEY_DEFERABILITY	 29
#define SYNTH_TABLE_FOREIGNKEY_DELETERULE	 30
#define SYNTH_TABLE_FOREIGNKEY_INDEX_INDEX	 31
#define SYNTH_TABLE_FOREIGNKEY_MANDATORY	 32
#define SYNTH_TABLE_FOREIGNKEY_MANY	 33
#define SYNTH_TABLE_FOREIGNKEY_MODELONLY	 34
#define SYNTH_TABLE_FOREIGNKEY_NAME	 35
#define SYNTH_TABLE_FOREIGNKEY_OLDNAME	 36
#define SYNTH_TABLE_FOREIGNKEY_REFERENCEDCOLUMNS	 37
#define SYNTH_TABLE_FOREIGNKEY_REFERENCEDMANDATORY	 38
#define SYNTH_TABLE_FOREIGNKEY_TABLE_OWNER	 39
#define SYNTH_TABLE_FOREIGNKEY_TABLE_REFERENCEDTABLE	 40
#define SYNTH_TABLE_FOREIGNKEY_UPDATERULE	 41
#define SYNTH_TABLE_INDEX_COLUMNS	 42
#define SYNTH_TABLE_INDEX_COMMENT	 43
#define SYNTH_TABLE_INDEX_DEFERABILITY	 44
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_COLUMNLENGTH	 45
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_COLUMN_REFERENCEDCOLUMN	 46
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_COMMENT	 47
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_DESCEND	 48
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_NAME	 49
#define SYNTH_TABLE_INDEX_INDEXCOLUMN_OWNER	 50
#define SYNTH_TABLE_INDEX_INDEXKIND	 51
#define SYNTH_TABLE_INDEX_INDEXTYPE	 52
#define SYNTH_TABLE_INDEX_ISPRIMARY	 53
#define SYNTH_TABLE_INDEX_KEYBLOCKSIZE	 54
#define SYNTH_TABLE_INDEX_NAME	 55
#define SYNTH_TABLE_INDEX_OLDNAME	 56
#define SYNTH_TABLE_INDEX_OWNER	 57
#define SYNTH_TABLE_INDEX_PRIMARYKEY	 58
#define SYNTH_TABLE_INDEX_UNIQUE	 59
#define SYNTH_TABLE_INDEX_WITHPARSER	 60
#define SYNTH_TABLE_INDICES	 61
#define SYNTH_TABLE_ISSTUB	 62
#define SYNTH_TABLE_ISSYSTEM	 63
#define SYNTH_TABLE_ISTEMPORARY	 64
#define SYNTH_TABLE_KEYBLOCKSIZE	 65
#define SYNTH_TABLE_LASTCHANGEDATE	 66
#define SYNTH_TABLE_MAXROWS	 67
#define SYNTH_TABLE_MERGEINSERT	 68
#define SYNTH_TABLE_MERGEUNION	 69
#define SYNTH_TABLE_MINROWS	 70
#define SYNTH_TABLE_MODELONLY	 71
#define SYNTH_TABLE_NAME	 72
#define SYNTH_TABLE_NEXTAUTOINC	 73
#define SYNTH_TABLE_OLDNAME	 74
#define SYNTH_TABLE_OWNER	 75
#define SYNTH_TABLE_PACKKEYS	 76
#define SYNTH_TABLE_PARTITIONCOUNT	 77
#define SYNTH_TABLE_PARTITIONEXPRESSION	 78
#define SYNTH_TABLE_PARTITIONTYPE	 79
#define SYNTH_TABLE_PASSWORD	 80
#define SYNTH_TABLE_RAIDCHUNKS	 81
#define SYNTH_TABLE_RAIDCHUNKSIZE	 82
#define SYNTH_TABLE_RAIDTYPE	 83
#define SYNTH_TABLE_ROWFORMAT	 84
#define SYNTH_TABLE_SUBPARTITIONCOUNT	 85
#define SYNTH_TABLE_SUBPARTITIONEXPRESSION	 86
#define SYNTH_TABLE_SUBPARTITIONTYPE	 87
#define SYNTH_TABLE_TABLE	 88
#define SYNTH_TABLE_TABLEDATADIR	 89
#define SYNTH_TABLE_TABLEENGINE	 90
#define SYNTH_TABLE_TABLEINDEXDIR	 91
#define SYNTH_TABLE_TEMPORARYSCOPE	 92
#define SYNTH_TABLE_TEMP_SQL	 93

#define SYNTH_COUNT	94

extern int   synth_search(char *w);
extern char *synth_keyword(int code);

#endif
