#ifndef _MWBKEY_HEADER

#define _MWBKEY_HEADER

#define MWBKEY_NOT_FOUND	-1
#define MWBKEY_ALGORITHM	  0
#define MWBKEY_AUTOINCREMENT	  1
#define MWBKEY_AVGROWLENGTH	  2
#define MWBKEY_CAPTION	  3
#define MWBKEY_CAPTIONXOFFS	  4
#define MWBKEY_CAPTIONYOFFS	  5
#define MWBKEY_CHARACTERSETNAME	  6
#define MWBKEY_CHECKSUM	  7
#define MWBKEY_CLOSED	  8
#define MWBKEY_COLLATIONNAME	  9
#define MWBKEY_COLOR	 10
#define MWBKEY_COLUMNLENGTH	 11
#define MWBKEY_COLUMNS	 12
#define MWBKEY_COLUMNSEXPANDED	 13
#define MWBKEY_COMMENT	 14
#define MWBKEY_COMMENTEDOUT	 15
#define MWBKEY_CONNECTIONS	 16
#define MWBKEY_CONNECTIONSTRING	 17
#define MWBKEY_CREATEDATE	 18
#define MWBKEY_CURRENTDIAGRAM	 19
#define MWBKEY_DATATYPEEXPLICITPARAMS	 20
#define MWBKEY_DEFAULTCHARACTERSETNAME	 21
#define MWBKEY_DEFAULTCOLLATIONNAME	 22
#define MWBKEY_DEFAULTVALUE	 23
#define MWBKEY_DEFAULTVALUEISNULL	 24
#define MWBKEY_DEFERABILITY	 25
#define MWBKEY_DELAYKEYWRITE	 26
#define MWBKEY_DELETERULE	 27
#define MWBKEY_DESCEND	 28
#define MWBKEY_DESCRIPTION	 29
#define MWBKEY_DRAWSPLIT	 30
#define MWBKEY_ENDCAPTIONXOFFS	 31
#define MWBKEY_ENDCAPTIONYOFFS	 32
#define MWBKEY_ENDFIGURE	 33
#define MWBKEY_EXPANDED	 34
#define MWBKEY_EXPRESSION	 35
#define MWBKEY_EXTRACAPTION	 36
#define MWBKEY_EXTRACAPTIONXOFFS	 37
#define MWBKEY_EXTRACAPTIONYOFFS	 38
#define MWBKEY_FIGURES	 39
#define MWBKEY_FLAGS	 40
#define MWBKEY_FOREIGNKEY	 41
#define MWBKEY_FOREIGNKEYS	 42
#define MWBKEY_FOREIGNKEYSEXPANDED	 43
#define MWBKEY_GENERATED	 44
#define MWBKEY_GENERATEDSTORAGE	 45
#define MWBKEY_HEIGHT	 46
#define MWBKEY_INDEX	 47
#define MWBKEY_INDEXKIND	 48
#define MWBKEY_INDEXTYPE	 49
#define MWBKEY_INDICES	 50
#define MWBKEY_INDICESEXPANDED	 51
#define MWBKEY_ISNOTNULL	 52
#define MWBKEY_ISPRIMARY	 53
#define MWBKEY_ISSTUB	 54
#define MWBKEY_ISSYSTEM	 55
#define MWBKEY_ISTEMPORARY	 56
#define MWBKEY_KEYBLOCKSIZE	 57
#define MWBKEY_LASTCHANGEDATE	 58
#define MWBKEY_LAYER	 59
#define MWBKEY_LEFT	 60
#define MWBKEY_LENGTH	 61
#define MWBKEY_LOCKED	 62
#define MWBKEY_LOCKOPTION	 63
#define MWBKEY_MANDATORY	 64
#define MWBKEY_MANUALSIZING	 65
#define MWBKEY_MANY	 66
#define MWBKEY_MAXROWS	 67
#define MWBKEY_MERGEINSERT	 68
#define MWBKEY_MERGEUNION	 69
#define MWBKEY_MIDDLESEGMENTOFFSET	 70
#define MWBKEY_MINROWS	 71
#define MWBKEY_MODELONLY	 72
#define MWBKEY_NAME	 73
#define MWBKEY_NEXTAUTOINC	 74
#define MWBKEY_OLDNAME	 75
#define MWBKEY_OWNER	 76
#define MWBKEY_PACKKEYS	 77
#define MWBKEY_PARTITIONCOUNT	 78
#define MWBKEY_PARTITIONEXPRESSION	 79
#define MWBKEY_PARTITIONKEYALGORITHM	 80
#define MWBKEY_PARTITIONTYPE	 81
#define MWBKEY_PASSWORD	 82
#define MWBKEY_PRECISION	 83
#define MWBKEY_PRIMARYKEY	 84
#define MWBKEY_RAIDCHUNKS	 85
#define MWBKEY_RAIDCHUNKSIZE	 86
#define MWBKEY_RAIDTYPE	 87
#define MWBKEY_REFERENCEDCOLUMN	 88
#define MWBKEY_REFERENCEDCOLUMNS	 89
#define MWBKEY_REFERENCEDMANDATORY	 90
#define MWBKEY_REFERENCEDTABLE	 91
#define MWBKEY_ROOTLAYER	 92
#define MWBKEY_ROWFORMAT	 93
#define MWBKEY_SCALE	 94
#define MWBKEY_SIMPLETYPE	 95
#define MWBKEY_STARTCAPTIONXOFFS	 96
#define MWBKEY_STARTCAPTIONYOFFS	 97
#define MWBKEY_STARTFIGURE	 98
#define MWBKEY_STATSAUTORECALC	 99
#define MWBKEY_STATSPERSISTENT	100
#define MWBKEY_STATSSAMPLEPAGES	101
#define MWBKEY_SUBPARTITIONCOUNT	102
#define MWBKEY_SUBPARTITIONEXPRESSION	103
#define MWBKEY_SUBPARTITIONKEYALGORITHM	104
#define MWBKEY_SUBPARTITIONTYPE	105
#define MWBKEY_SUMMARIZEDISPLAY	106
#define MWBKEY_TABLE	107
#define MWBKEY_TABLEDATADIR	108
#define MWBKEY_TABLEENGINE	109
#define MWBKEY_TABLEINDEXDIR	110
#define MWBKEY_TABLESPACE	111
#define MWBKEY_TEMPORARYSCOPE	112
#define MWBKEY_TEMP_SQL	113
#define MWBKEY_TOP	114
#define MWBKEY_TRIGGERSEXPANDED	115
#define MWBKEY_UNIQUE	116
#define MWBKEY_UPDATEBLOCKED	117
#define MWBKEY_UPDATERULE	118
#define MWBKEY_VISIBLE	119
#define MWBKEY_WIDTH	120
#define MWBKEY_WITHPARSER	121
#define MWBKEY_X	122
#define MWBKEY_Y	123
#define MWBKEY_ZOOM	124

#define MWBKEY_KWCOUNT	125

#ifdef __cplusplus
extern "C" {
#endif
extern int   mwbkey_search(char *w);
extern char *mwbkey_keyword(int code);

#ifdef __cplusplus
}
#endif
#endif
